#!/bin/bash

# Set up environment variables for petalinux

#######################################################
#
# Variables to adjust on a project basis
#
#######################################################
# Project name
export BOARD=te0808
export TARGET_NAME=wimmis02

# To copy bitstream to NFS share
export SCP_TARGET_MACHINE="vogelpi@bordcomputer"
export SCP_TARGET_PATH="~/zynqmp/share/"

# To copy images to SD card
export SD_BOOT_PARTITION=/run/media/${USER}/TE0808_BOOT

#######################################################
#
# Dependent variables
#
#######################################################
# Path to workspace for target system
export WORKSPACE_PATH=/scratch/${USER}/${BOARD}/petalinux/os/${TARGET_NAME}

# Path to prebuilt images
export PREBUILT_PATH=${WORKSPACE_PATH}/../../prebuilt

# Path to bitstream
export VIVADO_EXPORT_PATH=${WORKSPACE_PATH}/../../../vivado

# Path to images generated by PetaLinux
export IMAGE_PATH=${WORKSPACE_PATH}/images/linux
