#!/bin/bash

make ARCH=${KERNEL_ARCH} CROSS_COMPILE=${KERNEL_CROSS_COMPILE} -j${N_CORES_COMPILE} -Image O=out/juno-oe 
make ARCH=${KERNEL_ARCH} CROSS_COMPILE=${KERNEL_CROSS_COMPILE} -j${N_CORES_COMPILE} -Image O=out/juno-oe dtbs

